version: '3.8'
services:
  playwright:
    image: mcr.microsoft.com/playwright:latest
    container_name: playwright
    volumes:
      - ./playwright-tests:/tests
    working_dir: /tests
    environment:
      - NODE_ENV=development
      - TZ=Asia/Ho_Chi_Minh
    command: >
      bash -c "npm init -y && npm install express @playwright/test && node server.js"
    ports:
      - "13100:3000"