version: '3.8'
services:
  playwright:
    image: mcr.microsoft.com/playwright:latest
    container_name: playwright
    environment:
      - NODE_ENV=development
      - TZ=Asia/Bangkok # UTC+7
    ports:
      - "13100:3000"