version: '3.8'
services:
  playwright:
    image: mcr.microsoft.com/playwright:latest
    container_name: playwright
    volumes:
      - ./data:/app
    environment:
      - NODE_ENV=development
      - TZ=Asia/Bangkok # UTC+7
    command: >
      bash -c "npm init -y && npm install express @playwright/test playwright-extra playwright-extra-plugin-stealth express-rate-limit && node server.js"
    ports:
      - "13100:3000"