version: '3.8'
services:
  playwright:
    image: mcr.microsoft.com/playwright:latest
    container_name: playwright
    environment:
      - NODE_ENV=development
      - TZ=Asia/Bangkok # UTC+7
    command: >
      bash -c "mkdir -p /app && cp /data/compose/*/server.js /app/ && cd /app && rm -rf node_modules package-lock.json && npm cache clean --force && npm init -y && npm install express @playwright/test playwright-extra playwright-extra-plugin-stealth express-rate-limit && node server.js"
    ports:
      - "13100:3000"